### ISSUE TITLE
Adding Profile Photo not supported in 'Edit Profile'

### ISSUE THREAD

**Issue by AthiraLekshmiCV** [amfoss/club-website-2017#8]

**Comment by a0xnirudh** [comment]
IMHO this is a necessary option. As of now, if a profile pic is not added while signing up, there is no option to add it at a later stage. Also, once added, it cannot be changed again (or else admin should remove the account and should sign up again).

**Comment by tonythomas01** [comment]
@ash1794 : what do you think of http://amritafoss.in/register/update_profile_pic/
something went wrong somewhere ?

**Comment by ash1794** [comment]
Ah. I didn't close it for the exact same reason. What's happening is that the Image models are getting duplicated with just one file name. So when i do a get, it is returning multiple objects. In the ideal scenario there should have been only one object. But i'm guessing due to anomalities in the new_register view there are multiple objects of the Image model being created. So one work around is to manually login to the db, and go to images_profileimage and make sure there's only one entry for each of them. That should fix it. To verify that is the problem if you could upload the output for 
'select \* from images_profileimage' you'll see what i'm talking about.

**Comment by tonythomas01** [comment]
The issue still persists after https://github.com/amfoss/website/commit/8a7756938c098cdd3a1f98a6bfb8078676d82788

I have e-mail you the output of 'select \* from images_profileimage'. Can you please verify that was the issue ?

**Comment by tonythomas01** [comment]
Works now after the restart ! http://foss.amrita.ac.in/register/update_profile_pic/
When I try to change my profile pic, I get this error : 
NameError at /register/update_profile_pic/
global name 'instance' is not defined
Request Method: POST
Request URL:    http://foss.amrita.ac.in/register/update_profile_pic/
Django Version: 1.6
Exception Type: NameError
Exception Value:  
global name 'instance' is not defined
Exception Location: /home/domains/foss/fosswebsite/register/views.py in update_profile_pic, line 423
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:  
['/home/domains/foss/fosswebsite/foss/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/domains/foss/fosswebsite/foss/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/home/domains/foss/fosswebsite',
 '/home/domains/foss/fosswebsite/foss/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/domains/foss/fosswebsite/']
Server time:    Mon, 23 Feb 2015 14:25:35 +0530

**Comment by ash1794** [comment]
Fixing that. My mistake.
